### ISSUE TITLE
ValueError: astimezone() cannot be applied to a naive datetime

### ISSUE THREAD

**Issue by chlaudan** [TheBestMoshe/hebcal#1]
When attempting to run your first example (or nearly any):
time_info = hebcal.TimeInfo.now(latitude=40.089909, longitude=-74.216270)

Results in this:
>>> time_info = hebcal.TimeInfo.now(latitude=40.089909, longitude=-74.216270)
Traceback (most recent call last):
  File "<pyshell#3>", line 1, in <module>
    time_info = hebcal.TimeInfo.now(latitude=40.089909, longitude=-74.216270)
  File "/usr/local/lib/python3.5/dist-packages/hebcal/__init__.py", line 97, in now
    return cls(datetime.now(), **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/hebcal/__init__.py", line 70, in __init__
    self.date_time = proccess_datetime(date_time, timezone=self.timezone)
  File "/usr/local/lib/python3.5/dist-packages/hebcal/util/proccess_time.py", line 30, in proccess_datetime
    kwargs['timezone'])
  File "/usr/local/lib/python3.5/dist-packages/hebcal/util/proccess_time.py", line 50, in add_timezone_to_datetime
    return datetime.astimezone(pytz.timezone(timezone))
ValueError: astimezone() cannot be applied to a naive datetime
>>>

**Comment by TheBestMoshe** [comment]
This should be fixed by #2
